from __future__ import annotations

PILOT_ROUTE_SIGNATURES: tuple[str, ...] = (
    "GET /api/v1/health",
    "GET /api/v1/health/db",
    "GET /api/v1/health/observability",
    "GET /api/v1/health/ai",
    "GET /api/v1/health/offline-agent",
    "GET /api/v1/health/guardrails",
    "GET /api/v1/health/memory",
    "GET /api/v1/health/action-providers",
    "GET /api/v1/health/data-platform",
    "GET /api/v1/health/auth",
    "GET /api/v1/health/shelf-image",
    "GET /api/v1/health/audit-sink",
    "GET /api/v1/integrations/readiness",
    "GET /api/v1/integrations/pilot-gap-report?target=local",
    "GET /api/v1/integrations/activation-runbook?target=pilot",
    "GET /api/v1/integrations/discovery-packet?target=pilot",
    "GET /api/v1/integrations/ai-demo-activation-pack",
    "GET /api/v1/metrics/pilot",
    "GET /api/v1/manager/territory-summary?territory_code=WEST-01",
    "GET /api/v1/manager/approval-queue?territory_code=WEST-01",
    "POST /api/v1/manager/tasks",
    "GET /api/v1/manager/tasks?territory_code=WEST-01&status=OPEN",
    "GET /api/v1/manager/my-tasks?status=OPEN",
    "POST /api/v1/manager/tasks/{task_id}/status",
    "GET /api/v1/admin/audit-events?event_type=&rep_id=&resource_type=&limit=&cursor=",
    "GET /api/v1/admin/audit-events/{event_id}",
    "GET /api/v1/visits/today?territory_code=WEST-01&date=YYYY-MM-DD",
    "GET /api/v1/stores/{store_id}",
    "GET /api/v1/stores/{store_id}/alerts?limit=50&cursor=&min_risk_score=0.7",
    "GET /api/v1/stores/{store_id}/rgm-recommendations",
    "POST /api/v1/stores/{store_id}/shelf-image-analysis",
    "POST /api/v1/alerts/{alert_id}/feedback",
    "POST /api/v1/orders/drafts",
    "GET /api/v1/orders/drafts/{draft_id}",
    "POST /api/v1/approvals/{draft_id}/approve",
    "POST /api/v1/approvals/{draft_id}/reject",
    "POST /api/v1/orders/drafts/{draft_id}/submit-sandbox",
    "POST /api/v1/crm/visit-log-drafts",
    "POST /api/v1/sync/feedback-events",
    "POST /api/v1/agent/osa-summary",
    "POST /api/v1/agent/run",
    "GET /api/v1/audit/session/{session_id}",
)


REQUIRED_RESPONSE_FIELDS: dict[str, set[str]] = {
    "IntegrationReadinessResponse": {
        "activation_evidence_manifests",
        "activation_targets",
        "ai_demo_eval_validated",
        "ai_demo_next_actions",
        "provider_readiness",
        "runtime_validation_commands",
        "summary_provider",
    },
    "ActivationEvidenceManifestOut": {
        "required_artifacts",
        "required_env_keys",
        "sections",
        "target",
    },
    "ActivationEvidenceSectionOut": {
        "artifacts",
        "env_keys",
        "name",
        "notes",
        "required_for",
    },
    "PilotGapReportResponse": {
        "activation_targets",
        "blocking_gaps",
        "gap_count",
        "recommended_commands",
        "roadmap_items",
        "target",
    },
    "ActivationRunbookResponse": {
        "blocked_phase_count",
        "current_target",
        "final_outcome",
        "phase_count",
        "phases",
        "ready_phase_count",
    },
    "DiscoveryPacketResponse": {
        "defaulted_count",
        "gate_count",
        "missing_count",
        "next_actions",
        "owner_groups",
        "target",
    },
    "AIDemoActivationPackResponse": {
        "blockers",
        "config_checks",
        "eval_validated",
        "next_actions",
        "provider_ready",
        "required_artifacts",
        "required_commands",
        "required_env_keys",
        "stage",
        "summary_provider",
    },
    "AIDemoConfigCheckOut": {
        "name",
        "notes",
        "ready",
    },
}
