"""Document the Phase 1 mock data contract.

The backend MockOSAAdapter generates deterministic demo data in memory:
- WEST-01
- REP-001 through REP-005
- 25 stores
- 125 SKU alert rows

This script is intentionally non-mutating for Phase 1 because local data is generated
inside the adapter. It exists so the repo has the planned seed entrypoint.
"""


def main() -> None:
    print("Phase 1 mock data is generated by backend.adapters.osa.MockOSAAdapter")
    print("Territory: WEST-01")
    print("Reps: REP-001..REP-005")
    print("Stores: 25")
    print("Alerts: 125")


if __name__ == "__main__":
    main()

